<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Pagina;

class PaginasSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {
    $paginas = [
      ["descricao" => "<h2><strong>O que é Engenharia Social?</strong></h2><p><br></p><p>A <strong>engenharia social</strong> é uma técnica usada para manipular indivíduos a fim de obter informações confidenciais ou realizar ações que beneficiem o atacante. Ao contrário de outros tipos de ciberataques, a engenharia social não se concentra em explorar vulnerabilidades técnicas de sistemas ou redes, mas sim as falhas humanas. A ideia central é enganar a vítima, explorando as suas emoções, confiança ou desatenção para obter acesso a dados, sistemas ou recursos.</p><p><br></p><p>Esta prática tem se tornado uma das formas mais eficazes de ataque, pois os humanos são, frequentemente, o elo mais fraco na segurança de qualquer sistema. Mesmo com tecnologias avançadas de segurança, um ataque bem planeado de engenharia social pode ser suficiente para comprometer informações sensíveis.</p>", "ordem" => 1, "idUnidade" => 1],
      ["descricao" => '<h2><strong>Porque é que a Engenharia Social funciona?</strong></h2><p><br></p><p>A engenharia social baseia-se em aspetos psicológicos humanos que afetam a tomada de decisão. Os ataques são frequentemente projetados para criar um senso de urgência, medo ou empatia, o que faz com que as vítimas ajam impulsivamente sem pensar nas consequências.</p><p><br></p><p>Entre as emoções mais exploradas pelos atacantes estão:</p><p><br></p><ul><li><strong>Medo:</strong> Criar um senso de urgência ou ameaça, fazendo com que a vítima se sinta pressionada a agir rapidamente.</li></ul><p>                            Exemplo: "O seu sistema foi comprometido! Clique neste link para proteger a sua conta imediatamente."</p><p><br></p><ul><li><strong>Confiança:</strong> Aproveitar-se de uma relação pré-existente ou do status de autoridade para enganar a vítima.</li></ul><p>                                Exemplo: Um hacker a fazer-se passar por um colega de trabalho ou superior hierárquico.</p><p><br></p><ul><li><strong>Curiosidade:</strong> Enviar uma mensagem com um link ou anexo chamativo para que a vítima clique.</li></ul><p>                         Exemplo: "Você foi mencionando neste post, veja agora!"</p><p><br></p><ul><li><strong>Empatia:</strong> Manipular a vítima explorando a sua boa vontade e desejo de ajudar, como em casos de pedidos de ajuda urgentes.</li></ul><p><br></p><p>Estas táticas tornam os ataques de engenharia social extremamente difíceis de detetar e prevenir, uma vez que exploram características naturais e instintivas dos seres humanos.</p><p><br></p>', "ordem" => 2, "idUnidade" => 1],
      ["descricao" => "<h2><strong>Tipos Comuns de Ataques de Engenharia Social</strong><h2><p><br></p><p>Existem várias formas de ataques de engenharia social, que podem ocorrer de diversas maneiras. Algumas das técnicas mais comuns incluem:</p><p><br></p><ul><li><strong>Phishing:</strong> Envio de e-mails ou mensagens falsas, frequentemente a fazer-se passar por empresas ou instituições confiáveis, solicitando que o destinatário forneça dados pessoais ou faça uma ação (como clicar num link ou abrir um anexo).</li></ul><p><br></p><ul><li><strong>Spear Phishing:</strong> Similar ao phishing, mas mais direcionado e personalizado. O atacante pesquisa a vítima para tornar o ataque mais convincente e eficaz.</li></ul><p><br></p><ul><li><strong>Vishing:</strong> Uma forma de phishing via chamada telefónica. O atacante faz-se passar por uma entidade confiável, como um banco ou uma empresa, para obter informações sensíveis.</li></ul><p><br></p><ul><li><strong>Smishing:</strong> Ataques de phishing realizados através de mensagens de texto (SMS), onde o atacante tenta enganar a vítima para que clique num link ou forneça informações pessoais.</li></ul><p><br></p><ul><li><strong>Pretexting:</strong> O atacante cria uma falsa identidade (um pretexto) para obter informações. Este pode, por exemplo, fazer-se passar por um funcionário de uma empresa de suporte técnico para solicitar dados confidenciais.</li></ul><p><br></p><ul><li><strong>Tailgating:</strong> Um ataque físico onde o criminoso tenta acessar uma área restrita aproveitando-se da desatenção ou boa vontade de outra pessoa, como seguir alguém através de uma porta de segurança.</li></ul>", "ordem" => 3, "idUnidade" => 1],
      ["descricao" => '<h2><strong>Exemplos Reais de Engenharia Social</strong></h2><p><br></p><p><strong>A engenharia social pode acontecer tanto no ambiente online quanto no físico. Exemplos comuns incluem:</strong></p><p><br></p><ul><li><strong>Golpes por e-mail:</strong> Muitas vezes, os atacantes fazem-se passar por empresas ou bancos, solicitando que a vítima clique num link que lev a um site falso para roubo de credenciais.</li></ul><p><br></p><ul><li><strong>Golpe de "WhatsApp":</strong> O atacante faz-se passar por um amigo ou familiar e envia uma mensagem urgente solicitando dinheiro ou dados pessoais.</li></ul><p><br></p><ul><li><strong>Pretexting em empresas:</strong> O atacante liga para um funcionário fazendo-se passar por um colega ou prestador de serviços e pede informações ou acesso a áreas restritas da empresa.</li></ul>', "ordem" => 4, "idUnidade" => 1],
      ["descricao" => "<h2><strong>Como Evitar Ser Vítima de Engenharia Social?</strong></h2><p><br></p><p><strong>A principal defesa contra a engenharia social é a conscientização</strong>. As organizações devem treinar os seus funcionários para reconhecer sinais de ataques e agir de forma prudente em situações de risco. Algumas práticas de proteção incluem:</p><p><br></p><ul><li><strong>Desconfiar de solicitações inesperadas:</strong> Nunca forneça informações pessoais ou confidenciais, como senhas, em resposta a um e-mail, mensagem ou telefonema não solicitado.</li></ul><p><br></p><ul><li><strong>Verificar fontes:</strong> Em caso de dúvida, verifique sempre diretamente com a pessoa ou instituição envolvida. Não utilize os contactos fornecidos na mensagem ou no e-mail suspeito.</li></ul><p><br></p><ul><li><strong>Utilizar autenticação de dois fatores (2FA):</strong> Este mecanismo adiciona uma camada extra de segurança, tornando mais difícil para os atacantes acessarem sistemas ou contas, mesmo se souberem a sua senha.</li></ul><p><br></p><ul><li><strong>Desenvolver uma cultura de segurança:</strong> Todos os membros da organização devem estar cientes dos riscos da engenharia social e ser incentivados a relatar qualquer incidente suspeito.</li></ul>", "ordem" => 5, "idUnidade" => 1],
      ["descricao" => "<h2><strong>Conclusão</strong></h2><p><br></p><p>A engenharia social é uma técnica de ataque que explora a vulnerabilidade humana, tornando-se uma das formas mais eficazes de acesso a informações sensíveis. Entender como estes ataques funcionam e como se proteger é fundamental para evitar ser vítima de tais golpes. A educação continua e a implementação de práticas de segurança podem reduzir significativamente os riscos de ataques bem-sucedidos de engenharia social.</p>", "ordem" => 6, "idUnidade" => 1],
      ["descricao" => "<h2><strong>Quiz de Fixação</strong></h2><p><br></p><p><strong>1. O que define um ataque de Engenharia Social?</strong></p><p><br></p><p> A) Ataque técnico a sistemas</p><p> B) Manipulação de emoções humanas</p><p> C) Invasão por força bruta</p><p> D) Uso de antivírus para espiar</p><p><br></p><p>✅ Resposta: <strong>B)</strong></p>", "ordem" => 7, "idUnidade" => 1],
      ["descricao" => "<h2><strong>Quiz de Fixação</strong></h2><p><br></p><p><strong>2. Qual é o principal objetivo de um atacante social?</strong></p><p><br></p><p> A) Testar antivírus</p><p> B) Roubar senhas através de engenharia humana</p><p> C) Aprender sobre psicologia</p><p> D) Espiar empresas com drones</p><p><br></p><p>✅ Resposta: <strong>B)</strong></p>", "ordem" => 8, "idUnidade" => 1],
      ["descricao" => "<h2><strong>Quiz de Fixação</strong></h2><p><br></p><p><strong>3. Quem foi Kevin Mitnick?</strong></p><p><br></p><p> A) Desenvolvedor de antivírus</p><p> B) Político americano</p><p> C) Hacker que utilizava engenharia social</p><p> D) Fundador do Google</p><p><br></p><p>✅ Resposta: <strong>C)</strong></p>", "ordem" => 9, "idUnidade" => 1],
      ["descricao" => "<h2><strong>Quiz de Fixação</strong></h2><p><br></p><p><strong>4. Porque é que a engenharia social é perigosa mesmo com segurança digital forte?</strong></p><p><br></p><p> A) Porque ignora a tecnologia</p><p> B) Porque depende de erros humanos</p><p> C) Porque ataca somente redes sociais</p><p> D) Porque usa força bruta</p><p><br></p><p>✅ Resposta: <strong>B)</strong></p>", "ordem" => 10, "idUnidade" => 1],
      ["descricao" => "<h2><strong>Quiz de Fixação</strong></h2><p><br></p><p><strong>5. Qual das opções abaixo é exemplo de engenharia social?</strong></p><p><br></p><p> A) Quebra de senha com software</p><p> B) Atualização do sistema operativo</p><p> C) Enganar alguém para revelar dados por telefone</p><p> D) Uso de firewall</p><p><br></p><p>✅ Resposta: <strong>C)</strong></p>", "ordem" => 11, "idUnidade" => 1],
      
      
      ["descricao" => "<p>Caso sejas alvo, deves <strong>evitar interagir</strong>, <strong>reportar à equipa certa</strong> e <strong>alertar os colegas</strong>.</p>", "ordem" => 1, "idUnidade" => 2],
      ["descricao" => "<p>Uma <strong>cultura de segurança</strong> inclui <em>formação regular</em>, <em>comunicação</em> e <em>simulações de ataques</em>.</p>", "ordem" => 2, "idUnidade" => 2]
    ];

    foreach ($paginas as $pagina) {
      Pagina::create($pagina);
    }
  }
}
